### ISSUE TITLE
Баг с машинами.

### ISSUE THREAD

**Issue by chelog** [octothorp-team/public-dobrograd#143]
In GitLab by @furry on Jul 14, 2020, 19:29

https://youtu.be/z4_su4HXMts

**Comment by chelog** [comment]
In GitLab by @Wani4ka on Jul 14, 2020, 21:25

closed via commit 468dbbb06656e1284b22082b5d788a3e1daefc99

**Comment by chelog** [comment]
In GitLab by @Wani4ka on Jul 14, 2020, 21:30

mentioned in commit 468dbbb06656e1284b22082b5d788a3e1daefc99

**Comment by Furry** [comment]
> In GitLab by @Furry on Jul 14, 2020, 19:29
> 
> https://youtu.be/z4_su4HXMts

I'm a bit confused, was pinging me intentional?

**Comment by chelog** [comment]
@Furry sorry, I was running gitlab (self-hosted instance) issues migration script and it appears to ping users with same name across github. Wasn't intentional
