### ISSUE TITLE
Пневматика не убирается в инвентарь

### ISSUE THREAD

**Issue by chelog** [octothorp-team/public-dobrograd#314]
In GitLab by @Markus on Dec 28, 2020, 14:26

Раньше при попадании из пневматики в любую часть тела человека, у которого в руках тоже была пневматика, его оружие убиралось в инвентарь. Но сейчас это не происходит по непонятным причинам

**Comment by chelog** [comment]
In GitLab by @Wani4ka on Dec 30, 2020, 19:31

Исправлено в 8a78378aef9d9ce9aa61bf2539cf050b90383c57

**Comment by markus** [comment]
@chelog could you avoid mentioning @markus on these issues? It seems impossible for me to turn off notifications for this project and still receive notifications when I'm mentioned on other projects.

**Comment by chelog** [comment]
@markus sorry, I was running gitlab (self-hosted instance) issues [migration script](https://github.com/piceaTech/node-gitlab-2-github) and it appears to ping users with same name across github. Wasn't intentional. Transfer is finished and shouldn't ping you ever again

**Comment by markus** [comment]
No worries :)
