### ISSUE TITLE
Призрак ходит и всем мешает

### ISSUE THREAD

**Issue by FSBJI** [octothorp-team/public-dobrograd#527]
### Что наблюдается?

Призрак мещает действиям, когда он в них входит

### Как это должно работать?

Призрак входит в тебя из-за этого остановливается обыск, развязывание и т д.

### Как это повторить?

Умереть и ходить в человека за призрака

### Ошибки в консоли

```shell
-
```

### Обратная связь

ник крутой#8888

**Comment by chelog** [comment]
Для разработчиков: скорей всего, проблема в octolib.getUseTrace, он не фильтрует призраков

**Comment by chelog** [comment]
Исправил в недавнем коммите
