### ISSUE TITLE
Отсутствие немаркированых машин у детективов

### ISSUE THREAD

**Issue by BYTULK** [octothorp-team/public-dobrograd#528]
### Что наблюдается?

Уже на протяжении трёх дней у профессии "Детектив", отсутствую немаркированые машины, что нарушает атмосферу и концепцию их скрытности. Ранее Sighty должен был это сделать, на что он мне ответил положительно, но в течении 3-4 дней машины так и не появились.

### Как это должно работать?

Машины должны быть в меню Ф4 рядом с полицейскими, но в данный момент их нет.
![изображение](https://user-images.githubusercontent.com/90627314/133095610-e8eda3ef-48e7-4981-831d-dd51f1e47126.png)

### Обратная связь

Requiescat in pace#6517

**Comment by BYTULK** [comment]
Очевидно это связано с чем то у меня, но я не знаю с чем. Возможно нужно просто добавить вариант PO.

**Comment by chelog** [comment]
@Sighty8 сказал, что несколько раз перепроверил и это не проблема на нашей стороне. Вопросы такого характера, как выдача доступа лучше решить через канал #help в дискорде
