### ISSUE TITLE
Некорректное работа баллистического щита лейтенанта 

### ISSUE THREAD

**Issue by AzrikDream** [octothorp-team/public-dobrograd#531]
### Что наблюдается?

При стрельбе в район рук щита он выбивается из рук

### Как это должно работать?

Щит по идее невозможно выбить при стрельбе в него если это не крупный калибр

### Как это повторить?

Стрелок должен встать к примеру на лестничный проем смотреть вниз на лейтенанта он же в это время должен стоять ниже стрелка и щитом смотреть ему в район шеи, нападающий должен стрелять в район рук лейтенанта. 

### Ошибки в консоли

```shell
Нет.
```

### Обратная связь

АзрикДрим♪#1484

**Comment by chelog** [comment]
Не получилось повторить

![](https://i.imgur.com/DjmelZZ.png)
