### ISSUE TITLE
Ошибка при взятии полицейской профессии, после истечения блокировки профессии

### ISSUE THREAD

**Issue by pinq1fox** [octothorp-team/public-dobrograd#532]
### Что наблюдается?

Не берётся полицейская профессия после истечения блокировки профессии администратором, выдаёт в чат ошибку: "[#] Ты не можешь играть за полицейские профессии!"

### Как это должно работать?

После того, как срок блокировки профессии закончился, она вновь должна быть доступна.

### Как это повторить?

1. Администратору выдать блокировку игры за полицейского игроку;
2. После истечения блокировки, игроку необходимо подойти к табличке выбора профессии полиции;
3. Выбрать любую профессию из списка.

### Обратная связь

pinqfox#5910

**Comment by chelog** [comment]
Не получилось повторить

![](https://i.imgur.com/DjmelZZ.png)
