### ISSUE TITLE
Отсутствие панели на машине

### ISSUE THREAD

**Issue by BYTULK** [octothorp-team/public-dobrograd#533]
### Что наблюдается?

Отсутствие уровня топлива, передачи, скорость и прочее, что связано с управлением авто на Dimond кабриолет.
![Uploading изображение.png…]()

### Как это должно работать?

Должно быть как на всех остальных машинах.

**Comment by Kyper1** [comment]
Еще хочу добавить, что камеры зеркал, расположенных по бокам, слегка кривые. Сама текстурка зеркал закрывает всю видимость
