### ISSUE TITLE
Маленькие колеса у машин

### ISSUE THREAD

**Issue by BYTULK** [octothorp-team/public-dobrograd#630]
### Что наблюдается?

Очень уменьшен размер покупных колес у машин, в то время как стандартные выглядят нормально.

### Как это должно работать?

Все колеса должны быть одинакового размера.![изображение](https://user-images.githubusercontent.com/90627314/136347939-01221501-05b6-4f86-9ecc-5c84e3b38130.png)
![изображение](https://user-images.githubusercontent.com/90627314/136347908-2fecdfac-8e49-4a35-b489-e8c85d8acef8.png)
![изображение](https://user-images.githubusercontent.com/90627314/136347993-0437a1df-a603-4282-82c8-b690aabe00b3.png)

**Comment by chelog** [comment]
Не получается повторить, на разных автомобилях, и с разными моделями дисков все нормально, взял даже те же, что и на скриншоте из репорта

![](https://i.imgur.com/WBAMQtP.jpeg)
