### ISSUE TITLE
Отсутствие помещения на Бравери

### ISSUE THREAD

**Issue by delingar** [octothorp-team/public-dobrograd#676]
### Что наблюдается?

На сервере НДБГ на улице Бравери имеется помещение с серым фасадом (между угловым и гаражным помещениями), двери которого невозможно выкупить, так как для них не создано помещение

### Как это должно работать?

Помещение должно выкупаться игроком

### Обратная связь

Delingar#6465

**Comment by chelog** [comment]
Это ошибка настройки карты и с таким надо обращаться к администрации
