### ISSUE TITLE
Драгоценные камни

### ISSUE THREAD

**Issue by Kvadratik34** [octothorp-team/public-dobrograd#683]
### Что наблюдается?

В магазине имеются много различных драгоценных камней из которых можно сделать украшения, а после продать их  по заданию. Так вот, не знаю, так ли это планировалось, но не из всех камней можно сделать украшения, а именно из изумруда и топаза. 

### Как это должно работать?

Думаю, что из этих материалов (изумруда и топаза) должны делаться ювелирные изделия, а после продаваться в "Заданиях". 

### Как это повторить?

Зайти в крафты и посмотреть, что из изумруда и топаза никаких украшений сделать нельзя, также как и продать их в "Заданиях".

### Обратная связь

Кваdrатик#6760

**Comment by chelog** [comment]
Это пока что ошибка дизайна, но не баг, просто этим камням еще не сделано применения, так что закрываю
