### ISSUE TITLE
Отрезали руки

### ISSUE THREAD

**Issue by ghost** [octothorp-team/public-dobrograd#693]
### Что наблюдается?

Админ мне запретил краймить, понятия не имею как конкретно должен работать такой запрет, но по моему мне по сути отрубили руки, при попытке взять кирку у меня просто выскакивает в чате надпись [#] Ты сможешь использовать оружие через 2 месяца. По механу кирка никак не может навредить окружающим, почему 
я её не могу использовать даже просто в целях похода в шахту?

### Как это должно работать?

Кирка должна браться в руки.

### Как это повторить?

1) Попросить админа запретить тебе крайм. 2) Попытаться взять в руки кирку.

### Обратная связь

Nazi_boi1488#2324

**Comment by chelog** [comment]
Решено в [61251d7](https://github.com/octothorp-team/gmod-dobrograd/commit/61251d732e3a180e022b9ad2f6f0dc6c0b261e50)
