### ISSUE TITLE
Дух не дух

### ISSUE THREAD

**Issue by An1reyka** [octothorp-team/public-dobrograd#694]
### Что наблюдается?

За духа можно двигать упакованые трупы, мешая коронерам и т.п

### Как это должно работать?

Духи должны проходить сквозь них.

### Как это повторить?

Стать духом и взять упакованое тело.

### Обратная связь

An1reyka#7421

**Comment by ghost** [comment]
Аналогично за духа можно мешать: упаковывать труп, подбирать предметы, запаковывать в зип-пакеты вещи
