### ISSUE TITLE
Ошибка отображения онлайна НДБГ

### ISSUE THREAD

**Issue by LENFYS** [octothorp-team/public-dobrograd#712]
### Что наблюдается?

При заходе на сервер Новый Доброград всегда отображается 0 онлайна.

### Как это должно работать?

Вы сами знаете

### Как это повторить?

1.) Зайти на новый Доброград

### Ошибки в консоли

```shell
Её нет.
```

### Обратная связь

LENFYS#5324

**Comment by chelog** [comment]
Исправлено в одном из предыдущих коммитов
