### ISSUE TITLE
Сломанные гитары(Скриптовые ошибки и поломка положения)

### ISSUE THREAD

**Issue by Gelogy** [octothorp-team/public-dobrograd#747]
### Что наблюдается?

Привет! Последнее время с гитарами странная тема, они ужасно берутся в руки(Багается модель, а именно положение гитары в руках) и выдаёт скриптовую ошибку. 
https://imgur.com/a/09qSZo0

### Как это должно работать?

Гитары должны адекватно доставаться, не вызывая скриптовых ошибок.

### Как это повторить?

Взять гитару в руки из инвентаря.

### Ошибки в консоли

```shell
[local-octolib] addons/local-octolib/lua/weapons/octolib_custom/cl_init.lua:16: attempt to index local 'worldModel' (a nil value)
    1. unknown - addons/local-octolib/lua/weapons/octolib_custom/cl_init.lua:16
```

### Обратная связь

Norma Jumleu#0653

**Comment by Wani4ka** [comment]
Исправлено в octothorp-team/gmod-octolib@1fafd5855dd40b9adeb5bfe0ecfec8edbedc6069
