### ISSUE TITLE
Не закрываються входные двери в здание CSD на цдбг

### ISSUE THREAD

**Issue by QixelPixel** [octothorp-team/public-dobrograd#788]
### Что наблюдается?

Открываешь двери здания CDS (стеклянные) после чего не можешь их закрыть,

### Как это должно работать?

Двери должны закрываться

### Как это повторить?

1. Открываем двери

### Ошибки в консоли

```shell
нет
```

### Обратная связь

Кисель#1034

**Comment by inquizzyoff** [comment]
Передам левел дизайнерам для фикса
