### ISSUE TITLE
Не работает рация у полицейских (стандартная ветка игры)

### ISSUE THREAD

**Issue by ghost** [octothorp-team/public-dobrograd#816]
### Что наблюдается?

Звук радиопередачи идет, но появляется ошибка и ничего не работает

### Как это должно работать?

Нажал кнопку и говоришь

### Как это повторить?

Попробовать за полицейского поговорить по рации

### Ошибки в консоли

```shell
[core-voice] RunConsoleCommand: Command is blocked! (+voicerecord)
  1. nextevent - addons/core-voice/lua/talkie/client.lua:252
   2. unknown - addons/util-dlib/lua/dlib/modules/hook.lua:1057
```

### Обратная связь

Easylemon#4604

**Comment by Wani4ka** [comment]
Исправлено в octothorp-team/gmod-dobrograd@ff3f40a5387e6ebed872390ff780bb9a67e44dfe
