### ISSUE TITLE
Сломаный лед на цдбг

### ISSUE THREAD

**Issue by Unknow123456789** [octothorp-team/public-dobrograd#898]
### Что наблюдается?

Не весь лед как лед, то есть я ишел по льду на центральном и провалился, а не которая часть льда вобще не скользит.

### Как это должно работать?

зафризиь лед что бы можно было ходить и скользить.

### Как это повторить?

просто походи. но могу показать демку в дискорде

### Обратная связь

Фил#6211

**Comment by inquizzyoff** [comment]
Лед в таком состоянии только в речке, передам дизайнерам окружения, в последствии пофиксим. Сейчас применил небольшой костыль
