### ISSUE TITLE
Неработающая исповедь в церкви. 

### ISSUE THREAD

**Issue by pizpi** [octothorp-team/public-dobrograd#907]
### Что наблюдается?

Невидимая стенка на которую назначено действие, а сам крест прозрачный.

### Как это должно работать?

На кресте действие исповеди.

### Как это повторить?

Сейчас наблюдается каждый день.

### Ошибки в консоли

```shell
getpots
```

### Обратная связь

P1zpi#5040

**Comment by inquizzyoff** [comment]
Все работает правильно, действие для молитвы привязано к невидимой стенке, которая стоит перед крестом
