### ISSUE TITLE
Модели DPD не на той профессии

### ISSUE THREAD

**Issue by Bandit20091** [octothorp-team/public-dobrograd#931]
### Что наблюдается?

Модели ДПД наложились на седьмую внешность профессии серверной полиции
![unknown](https://user-images.githubusercontent.com/42312897/155098779-f7cf8539-57ca-411d-bb4a-395b913cab40.png)

### Как это должно работать?

Должна быть своя модель, а не модель DPD

### Как это повторить?

1. Взять профессию серверного полицейского
2. Подойти к шкафчику и выбрать седьмую внешность

### Ошибки в консоли

```shell
-
```

### Обратная связь

Бандит2009#3976

**Comment by Wani4ka** [comment]
исправлено
