### ISSUE TITLE
Сломанное название профессии DPD в Tab

### ISSUE THREAD

**Issue by Kilo-7** [octothorp-team/public-dobrograd#933]
### Что наблюдается?

![jNuTViG 1](https://user-images.githubusercontent.com/96554302/155848648-f7e58468-d998-4ac9-a55c-438a4d4099f1.png)

### Как это должно работать?

Каждый ранг должен нормально называться в tab'е, а не как DPD

### Обратная связь

Kilo-7#0001

**Comment by Wani4ka** [comment]
Исправлено в octothorp-team/gmod-dobrograd@4e2e0ede68f934ccd8cfc23a2c6518f5cd0fc29c
