### ISSUE TITLE
У детективов dpd забрали немаркированные автомобили

### ISSUE THREAD

**Issue by Cactu7** [octothorp-team/public-dobrograd#935]
### Что наблюдается?

У детективов на F4 должны быть доступны немаркированные автомобили, но после недавнего обновления они пропали

### Как это должно работать?

У детективов должен быть доступ к немаркированным авто

### Как это повторить?

1. Взять профессию детектива
2. Посмотреть доступный транспорт на F4

### Обратная связь

cactus#8202

**Comment by Wani4ka** [comment]
Исправлено в octothorp-team/gmod-dobrograd@a19fd7db403d0eac783d99d005bf7547b030cfc2
