### ISSUE TITLE
Сломались анмаркеды

### ISSUE THREAD

**Issue by BozeDaiMneSil** [octothorp-team/public-dobrograd#939]
### Что наблюдается?

В "гараже" находясь на профессии детектива отсутствует анмаркед автомобили

### Как это должно работать?

Они должны быть

### Как это повторить?

Открываем F4
Заходим в вкладку гараж находясь в профессии детектива
И наблюдаем отсутствие 

### Ошибки в консоли

```shell
Не наблюдается (Как минимум в консоле я ничего не нашёл)
```

### Обратная связь

GenDot#9602

**Comment by Wani4ka** [comment]
Не получается повторить (возможно, уже пофиксил ранее)

![](https://i.imgur.com/CIdG0zh.png)
