### ISSUE TITLE
меня забанили по ошибке 

### ISSUE THREAD

**Issue by sumaist444** [octothorp-team/public-dobrograd#940]
### Что наблюдается?

у меня вылетел сервер 

### Как это должно работать?

я неправильно настроил css 

### Как это повторить?

неправильно скачать папку css

### Ошибки в консоли

```shell
ее нет
```

**Comment by Wani4ka** [comment]
Заявки на разбан подаются на форуме. Недостаточно информации, чтобы считать это багом
