### ISSUE TITLE
Баг с формой 

### ISSUE THREAD

**Issue by TheQwez** [octothorp-team/public-dobrograd#942]
### Что наблюдается?

В момент экипирования формы в полицейском департаменте, форма выдается но нельзя получить фуражку или кепку даже при том что галочка стоит 

### Как это должно работать?

подходишь к экипировочной и нажимаешь взять форму, ставя галочку ты не можешь взять фуражку, кепку  так как она не выдается

### Как это повторить?

просто прийти и попробовать взять форму и при этом поставить галочку на "Головной убор"

### Ошибки в консоли

```shell
не наблюдал.
```

### Обратная связь

TheQwez#8994

**Comment by Wani4ka** [comment]
Исправлено в octothorp-team/gmod-dobrograd@e7dcfa1c9f3370622fe31ba53132829940c824e8
