### ISSUE TITLE
Баг с множителем темноты.

### ISSUE THREAD

**Issue by Kyper1** [octothorp-team/public-dobrograd#946]
### Что наблюдается?

Передвигаясь по карте, периодически экран темнеет. Я захожу в настройки и ставлю множитель темноты на минимум. Далее закрываю настройки и проблема не исчезает. Захожу обратно в настройки и наблюдаю, что множитель темноты стоит все так же по умолчанию - 0.5

### Как это должно работать?

Как и раньше, сдвинул ползунок в одну сторону - он остается в этом месте. 

### Как это повторить?

1) Сместить позицию ползунка множителя темноты на любую другую позицию. 
2) Перейти в другую вкладку, к примеру, в "Управление". 
3) Закрыть настройки и открыть обратно. 
4) Вернуть к множителю темноты и, вуаля, значение обратно сместилось на 0.5

### Обратная связь

Captain-.-#5023

**Comment by Wani4ka** [comment]
Проблема скорее со стороны карты, сообщил об этом мапперу. В игре исправлено с помощью серверной настройки
