### ISSUE TITLE
Не работает возможность "Переместить все" \ "Переместить количество"

### ISSUE THREAD

**Issue by KillerBunny031** [octothorp-team/public-dobrograd#954]
### Что наблюдается?

Отсутствие возможности перенести определенное кол-во предметов или все сразу. 

### Как это должно работать?

Должно переноситься указанное число предметов или все сразу

### Как это повторить?

https://user-images.githubusercontent.com/87093007/162475177-9c1c5f50-dd4d-4730-a247-23ca478d96e0.mp4

### Ошибки в консоли

```shell
Отсутствуют
```

### Обратная связь

KillerBunny#0905

**Comment by chelog** [comment]
Это один предмет, когда пишется 100/100, это процент использования
