### ISSUE TITLE
Огромный, мать его, мужик!

### ISSUE THREAD

**Issue by aniastria** [octothorp-team/public-dobrograd#959]
### Что наблюдается?

Проп, похоже связанный с масленницой. Он очень крупный, и любой игрок может его ставить.
models/pretmodels/halloween_wickerman.mdl

### Как это должно работать?

Запретить возможность обычным смертным ставить этот проп.

### Как это повторить?

gm_spawn models/pretmodels/halloween_wickerman.mdl в консоль, или же найти самому в спавн меню. 

### Ошибки в консоли

```shell
-
```

### Обратная связь

А у тебя табуретки нету#0766

**Comment by NyashMyash99** [comment]
При попытке создать этот объект выдаётся ошибка `[#] Этот объект слишком большой`, где получилось его поставить?

UPD: Проверили, ставится везде, но только у оставившего отчёт.

**Comment by chelog** [comment]
Заблокировали на серверах возможность ставить эту модель
